### ISSUE TITLE
My research area is NLP.  I confused that the framework pretrain-finetune-distill comes from CV, and then used in NLP. But the paper use this framework in CV recently. 

### ISSUE THREAD

**Issue by lbda1** [google-research/simclr#100]

**Comment by chentingpc** [comment]
Sorry, I didn't get your question, do you mind articulate it? In SimCLRv2, we show "unsupervised pretraining" and "self-training / distillation with unlabeled data" could work well together for semi-supervised setting.

**Comment by lbda1** [comment]
Thank you for your reply.
The framework in the paper is the same as NLP's.
I am confused that what's the difference between this paper and NLP's.
If there's any offense here, I'm sorry at first.



在 2020-12-04 04:36:17，"Ting Chen" <notifications@github.com> 写道：

Sorry, I didn't get your question, do you mind articulate it? In SimCLRv2, we show "unsupervised pretraining" and "self-training / distillation with unlabeled data" could work well together for semi-supervised setting.

**Comment by chentingpc** [comment]
Yes, the "unsupervised pretrain -> supervised finetune -> distill" is pretty common in NLP nowadays, but this is not the case for CV, we showed the process could work very well for CV (especially semi-supervised learning). The main differences are in how one performs pretraining (SimCLRv2 on ResNet vs BERT on transformer), and how one does distillation (whether or not using unlabeled examples). Let me know if anything is still unclear.

**Comment by lbda1** [comment]
Thank you for replay.



At 2020-12-05 08:52:03, "Ting Chen" <notifications@github.com> wrote:

Yes, the "unsupervised pretrain -> supervised finetune -> distill" is pretty common in NLP nowadays, but this is not the case for CV, we showed the process could work very well for CV (especially semi-supervised learning). The main differences are in how one performs pretraining (SimCLRv2 on ResNet vs BERT on transformer), and how one does distillation (whether or not using unlabeled examples). Let me know if anything is still unclear.
