### ISSUE TITLE
Hello, could you tell me how to modify the code to use another data set for training and verification?

### ISSUE THREAD

**Issue by dmndxld** [google-research/simclr#106]
Hello, I am a Chinese university student.

**Comment by dmndxld** [comment]
Maybe could you tell me how to modify the code to use another data set for training and verification?

**Comment by chentingpc** [comment]
Hi, you could simply set `use_tpu=False` and it will then use GPU when it's available. For the dataset, you could either use one in [tensorflow datasets ](https://www.tensorflow.org/datasets/catalog/) or set it up use [tf.data.Dataset](https://www.tensorflow.org/api_docs/python/tf/data/Dataset)

**Comment by dmndxld** [comment]
Thank you for your quick reply. I have solved it now.

**Comment by here101** [comment]
> Thank you for your quick reply. I have solved it now.

Oh,dear, I have confronted with the same questions as you,how can you solve the problem.
Thanks a lot advance.
