### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by gscahhh** [google-research/simclr#107]
Hi, what's the python version?

**Comment by chentingpc** [comment]
it should work with both python 2 and 3.

**Comment by gscahhh** [comment]
> it should work with both python 2 and 3.

thanks, when I debug the procedure using pycharm breakpoint, why can't I go to the train_multiple_steps and single_step functions?

**Comment by chentingpc** [comment]
You should be able to break within those functions. You could comment out the tf.function to allow full eager mode (where you'll able to see the tensor value as you break).
