### ISSUE TITLE
Short and Quick Question on TPU/GPU usage

### ISSUE THREAD

**Issue by yaohungt** [google-research/simclr#11]
Hi Ting, 

Thanks for sharing all these, it's amazing and elegant. One quick question:

I never used TPU, and I'm very new to TensorFlow. I would like to test your code on GPU(s). The pretraining works, but I get a problem with finetuning.

Shall line 369 in run.py be
`sliced_eval_mode = tf.estimator.tpu.InputPipelineConfig.PER_HOST_V1`
rather than 
`sliced_eval_mode = tf.estimator.tpu.InputPipelineConfig.SLICED`
to enable GPU usage?

If using SLICED, my terminal told me SLICED could only be used when using TPU(s).

**Comment by chentingpc** [comment]
Thanks for reporting the issue. Yes, please use `InputPipelineConfig.PER_HOST_V1` instead of `InputPipelineConfig.SLICED` for now, and I will fix this in the next commit.

**Comment by yaohungt** [comment]
Thanks! Issue closed.

**Comment by chentingpc** [comment]
FYI, this is now fixed in https://github.com/google-research/simclr/commit/f3ca72f7efc085ad4abdb65f7a63459d9cfda78f

**Comment by yaohungt** [comment]
thanks!
