### ISSUE TITLE
Mismatch in number of parameters for the pre-trained weights and that obtained from model architecture.

### ISSUE THREAD

**Issue by Anuj040** [google-research/simclr#118]
To match the number of parameters provided in the README.md for sk_ratio=1.0 setting, should not it be "min" instead of "max", in the following line of code?
https://github.com/google-research/simclr/blob/3ad6700c1b139ee18e43f73546b7263a710de699/tf2/resnet.py#L242
On my end for Resnet-50 with width multiplier = 1, I get 38,700,384 parameters with "max" and 35,277,408 parameters with "min".
For width multiplier = 2, 154,526,400 for "max" versus 140,133,568 for "min"

**Comment by chentingpc** [comment]
The architecture should be the way it is. Did you exclude both supervised head and projection head when you compute the param count? It should just include the backbone. As a sanity check, you could also compute resnet-50 without sk to see if that works out

**Comment by Anuj040** [comment]
Yes, I have excluded supervised head and projection head. I am working with [r50_1x_sk1](https://console.cloud.google.com/storage/browser/simclr-checkpoints-tf2/simclrv2/pretrained/r50_1x_sk1/)
and when I look into it,  the following is the number of parameters I see. Now, I am trying extract "resnet" weights.

![image](https://user-images.githubusercontent.com/66895104/112562053-d0013a00-8e19-11eb-8905-2a62d47e6192.png)


Now, on my end when I define the architecture for "resnet-50", which matches the parameters mentioned in "README".
![image](https://user-images.githubusercontent.com/66895104/112562784-697d1b80-8e1b-11eb-8622-9cbc5e523ef0.png)

Following is when I define the resnet-50-sk1 architecture with "min"
![image](https://user-images.githubusercontent.com/66895104/112562594-f378b480-8e1a-11eb-8292-2209a741abee.png)

Following is when I define the resnet-50-sk1 architecture with "max"
![image](https://user-images.githubusercontent.com/66895104/112562754-59fdd280-8e1b-11eb-9041-b726e5c0e12a.png)

Now, I understand that the paper (https://arxiv.org/pdf/1903.06586.pdf) recommends it to be a "max" which means the resnet.py script is the way it is supposed to be. But somehow the number of parameters in the saved model file are corresponding to the "min" definition.

**Comment by chentingpc** [comment]
Our SK architecture is NOT exactly following the original paper since we didn't use grouped conv (and there may be other minor differences), so if you construct your network exactly following their paper, you may see different param count than us. 

See this [link](https://github.com/google-research/simclr/blob/3ad6700c1b139ee18e43f73546b7263a710de699/colabs/load_and_inference.ipynb) for how we computed the parameter count.

**Comment by Anuj040** [comment]
I mentioned the paper just for reference but the above parameter count is as per the architecture defined in your _resnet.py_, which gives me the parameter count matching with the saved model's parameter count only if I replace "max" with " min" at the mentioned location.

**Comment by chentingpc** [comment]
![image](https://user-images.githubusercontent.com/1329361/112571904-63f1e800-8dbf-11eb-8db3-66c2799cdf4b.png)

**Comment by Anuj040** [comment]
Hmmm, it seems there is some miscommunication happening here. 

I am not disputing the fact that the number of parameters in the saved model is 35 million. What I am discussing here is that to have a model architecture with "35 million" parameters I had to use "min" instead of " max".

If I use "max", as is in the current code, I get an architecture with "38 million" parameters.
I have also included the snapshots for the same in my previous comments.

Maybe, instead of counting the parameters for the saved model, you can trying saving a new models with "min" and "max" settings and verify my claim.

**Comment by chentingpc** [comment]
I can confirm it has always been `mid_dim = max(int(filters * sk_ratio), min_dim)` for all resnets with sk, including those saved checkpoints. You should be able to load the checkpoints to current code to verify that both code and checkpoint are consistent.

**Comment by Anuj040** [comment]
Thanks a lot for your time.
