### ISSUE TITLE
About color histogram in the paper

### ISSUE THREAD

**Issue by deepneuralnetworks** [google-research/simclr#121]
Hello thanks for the code.

I recently studied about contrastive learning and have some questions about _color histogram_ section.

Q1. In the paper, the color histogram doesn't seem to represent values from RGB. Are they from a gray-scaled image? 

Q2. I've tried to get some patches through random cropping but the color histograms are not similar to each other as much as in the paper. Is there an any guidance to perform the experiment?

Q3. When performing an ablation study about combination of augmentation, the paper randomly cropped and resized the original images at the beginning. Does this strategy not only unify the size, but also get diverse view?

It was very exciting to read the paper and I hope to reproduce the experiment by myself soon.

**Comment by chentingpc** [comment]
A1: As noted in Figure 6. Histograms are created over all RGB channels, i.e. you just need to flatten the whole RGB image into a long vector and plot the histogram.

A2: The similarity in histogram depends on the specific image you select, so you may want to try different images (e.g. the dog image in the original paper). Also, make sure you're not applying data augmentation to the image that you compute the histogram with.

A3: Yes, random cropping creating diverse views of the same image (e.g. Figure 4b vs 4c).

**Comment by deepneuralnetworks** [comment]
Thank you for the reply!
