### ISSUE TITLE
Question about semi-supervised evaluation procedure?

### ISSUE THREAD

**Issue by freshman0213** [google-research/simclr#122]
Hi, 

I wonder what's the exact procedure you perform semi-supervised fine-tuning.
I see that you mentioned in the paper and some previous issues that you only fine-tune the base network with limited labeled data. 
So does that mean that we don't need to add a classification head at the end of the base network to perform the fine-tuning?
I'm a little bit confused since in linear evaluation, we would need to add a linear classifier on the top of the fixed features, but you mentioned that you only fine-tune the base network under semi-supervised evaluation.

Thanks.

**Comment by chentingpc** [comment]
You still need to add the classification head for fine-tuning. When we say just fine-tune the base network, it really means we throw away the projection head during fine-tuning, not that we don't need to add a new classification head.

**Comment by freshman0213** [comment]
Thanks for your reply. 
Just to make it clear. Does the architecture of the new classification correspond the line 80-89 in model.py, which consists of a projection head and a linear layer?

**Comment by chentingpc** [comment]
the classification head is just a linear layer.

**Comment by freshman0213** [comment]
OK. Thanks a lot.
