### ISSUE TITLE
Self-distillation models

### ISSUE THREAD

**Issue by chigur** [google-research/simclr#130]
Hi,

I was wondering if the self-distillation models are also made available? I was looking into the [distill_1pc](https://console.cloud.google.com/storage/browser/simclr-checkpoints/simclrv2/distill_1pct) and [distill_10pct](https://console.cloud.google.com/storage/browser/simclr-checkpoints/simclrv2/distill_1pct) folders, and it seems they are distilled from R151-3x-SK. Am I right? The description of these directories is not really clear. I am particularly interested in the self-distilled ResNet-50 models (both 1% and 10%).

![simclr-models](https://user-images.githubusercontent.com/3609566/118872983-32753480-b8b7-11eb-9f89-b244611931a3.png)

**Comment by chentingpc** [comment]
Unfortunately the only self-distilled model available in the gcs is r152_3x_sk1, under the directory of `simclr-checkpoints/simclrv2/distill_1pct/r152_3x_sk1/r152_3x_sk1`

**Comment by chigur** [comment]
I see. Thanks a lot. :)
