### ISSUE TITLE
fine-tuning support?

### ISSUE THREAD

**Issue by slala2121** [google-research/simclr#133]
I see flags in the tf2/run.py related to finetuning e.g., fine_tune_after_block, etc. I am curious if this is indeed is supported or we should emulate the finetune colab instead? Thanks.

**Comment by chentingpc** [comment]
yes, that should be supported. feel free to check out [this](https://github.com/google-research/simclr/blob/3ad6700c1b139ee18e43f73546b7263a710de699/tf2/resnet.py#L619) to see how it works.

**Comment by slala2121** [comment]
Great, thanks.
