### ISSUE TITLE
Tensorflow version in requirements.txt

### ISSUE THREAD

**Issue by rgeirhos** [google-research/simclr#14]
Hey there, thanks for making this available, much appreciated!

Quick question: running `pip install -r requirements.txt` results in the following error: `Could not find a version that satisfies the requirement tensorflow==1.15`. Any ideas on what I should be doing differently?

**Comment by chentingpc** [comment]
are you using python2? I may be wrong, but I think upgrade to python3 should solve this. Alternatively you can try other tf versions, it may work with 1.14.

**Comment by rgeirhos** [comment]
Thank you for your prompt reply.

I was using python3, but the problem was connected to the pip version: upgrading pip from 18.1 to the most recent version 20.0.2 solved the problem.
