### ISSUE TITLE
data normalization

### ISSUE THREAD

**Issue by jiesonshan** [google-research/simclr#15]
Thanks Ting for open-sourcing the code and checkpoints. which method about data normalization in the ptoject？ I can't find it

**Comment by alisher0717** [comment]
Have you get to know which normalization has been applied to input images? Is it just rescaling into [0,1] range (img/255) or does it use ImageNet normalization?

**Comment by chentingpc** [comment]
https://github.com/google-research/simclr/blob/81e63a27be8b400a268cd4e1710af7590d172a36/data_util.py#L513
