### ISSUE TITLE
 Unknown command line flag 'variable_schema'

### ISSUE THREAD

**Issue by liuzheyu1998** [google-research/simclr#156]
Hi, I am trying to fine tune the linear head after the pretraining using the command: 
python run.py --mode=train_then_eval --train_mode=finetune \
  --fine_tune_after_block=4 --zero_init_logits_layer=True \
  --variable_schema='(?!global_step|(?:.*/|^)Momentum|head)' \
  --global_bn=False --optimizer=momentum --learning_rate=0.1 --weight_decay=0.0 \
  --train_epochs=100 --train_batch_size=512 --warmup_epochs=0 \
  --dataset=cifar10 --image_size=32 --eval_split=test --resnet_depth=18 \
  --checkpoint=/tmp/simclr_test --model_dir=/tmp/simclr_test_ft --use_tpu=False

However, it gives me an error of: FATAL Flags parsing error: Unknown command line flag 'variable_schema'.

I then tried to remove --variable_schema='(?!global_step|(?:.*/|^)Momentum|head)', and it gives me another error of tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /tmp/simclr_test: Failed precondition: /tmp/simclr_test; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?

I wonder if anyone knows how to fix that, and any advice will be appreciated. Thank you.

**Comment by chentingpc** [comment]
Are you using tf1 or tf2? `variable_schema` is only available in the tf1 version.

**Comment by liuzheyu1998** [comment]
I was using tf2, thank you.
