### ISSUE TITLE
About classifier architecture for fine tuning

### ISSUE THREAD

**Issue by omiita** [google-research/simclr#17]
Thank you for your impressive work. 
I'm reading your paper and wondering the architecture of SimCLR's classifier.

From my understanding, you used an l2-regularized multinomial logistic regression classifier for linear evaluation with frozen SimCLR. But, **which classifier is used for fine-tuning?** Did you use l2-regularized multinomial logistic regression classifier or something like non-linear MLP for fine-tuning?

Hope to hear from you soon.
Thanks in advance!

**Comment by chentingpc** [comment]
it is a linear classifier as you can see in https://github.com/google-research/simclr/blob/f3ca72f7efc085ad4abdb65f7a63459d9cfda78f/model_util.py#L127

**Comment by omiita** [comment]
Thank you for your response.

> it is a linear classifier as you can see in

Then, why didn't you use a non-linear classifier such as MLP for fine tuning in your paper?
Intuitively, it seems MLP work better in the case of fine tuning...?

**Comment by chentingpc** [comment]
So we have two ways of fine-tuning: (1) train a linear classifier on the fixed features (i.e. fixing the weights of base network), this is suboptimal in performance but most SSL literatures benchmark in this way and it is correlated with other downstream performance in general; (2) train a linear classifier at the same time adjust all weights in base network (i.e. fine-tune all layers). We didn't use MLP on fixed features, but I expect it to be better than linear classifier, and typically no better than fine-tuning all layers.
