### ISSUE TITLE
tf2 saved_models with no projection_head output

### ISSUE THREAD

**Issue by Maryeon** [google-research/simclr#181]
Hi,
the model loaded from tf2 saved_model checkpoints does not have "projection_output" in its outputs. While according to the README, it should have.

**Comment by chentingpc** [comment]
They should be there for tf1 hub models (e.g.
gs://simclr-checkpoints/simclrv2/pretrained/r50_1x_sk0/hub/), but not for
the finetuned ones (e.g.
gs://simclr-checkpoints/simclrv2/finetuned_100pct/r50_1x_sk0/hub/).
