### ISSUE TITLE
Pretrained checkpoint for projection head

### ISSUE THREAD

**Issue by jlindsey15** [google-research/simclr#19]
Hi -- I was wondering if it would be possible to include the projection head (for the SimCLR objective) in the model checkpoints?  The current checkpoints only seem to include the supervised projection head ("head_supervised") but not the unsupervised head ("head_contrastive")

**Comment by chentingpc** [comment]
We don't have an immediate plan for adding the projection head into the release checkpoint at this point, though we may consider it for a potential future update. In the meantime, an alternative is to consider training it yourself, with the rest of network kept fixed.

**Comment by bhat-prashant** [comment]
Hi, is there any plan in the near future to release models with projections heads? Please let me know. Thanks.

**Comment by chentingpc** [comment]
I believe the projection head is available in simclrv2 pretrain checkpoints (gs://simclr-checkpoints/simclrv2/pretrained). Let me know if you don't see them.
