### ISSUE TITLE
Reported imagenet results (e.g., Table 6) base on the validation set?

### ISSUE THREAD

**Issue by BierOne** [google-research/simclr#214]
Hi! 

Thanks for this outstanding work! Are the results reported (e.g., Table 6 and Figure 9) in your paper stem from the Imagenet validation set? Because I didn't find any statement about which split (val/test) you employed :)

Thanks.

**Comment by chentingpc** [comment]
reported imagenet results are from val split (following the common practice
used in prior work).

**Comment by BierOne** [comment]
Thank you!
