### ISSUE TITLE
How did you choose 1% imagenet data?

### ISSUE THREAD

**Issue by Heonjin** [google-research/simclr#24]
Hi.

How did you choose 1% imagenet data? To do the few-shot learning/semi-supervised learning, choosing labeled images are important. and I'd like to ask how you chose the images out of the whole imagenet dataset.

Thanks.

**Comment by chentingpc** [comment]
We have released 1%/10% imagenet subset data in tensorflow datasets with description on  sampling: https://tensorflow.google.cn/datasets/catalog/imagenet2012_subset

**Comment by Heonjin** [comment]
I wonder how you sampled these 13000/128000 images from ILSVRC-2012. Are they chosen randomly? How did you make these sets? I guess You might not have chosen the samples but if one of your team members chose them, please ask them how.

**Comment by simonster** [comment]
There are 12811 images (1% of 1281167 rounded down) consisting of either 12 or 13 for each class (i.e., the subset is as close to class-balanced as possible). Which classes have 12 and which have 13 was selected randomly, as were the images included.

**Comment by Heonjin** [comment]
@simonster Oh I see. Thanks.
