### ISSUE TITLE
Possible to include repos that minimally implements SimCLR in Keras

### ISSUE THREAD

**Issue by sayakpaul** [google-research/simclr#31]
Hi @chentingpc,

I was wondering if it is possible to list repositories that implement SimCLR minimally in a friendlier format with Keras or PyTorch. I think a lot of people might benefit from that. WDYT?

**Comment by chentingpc** [comment]
Sure, can you provide some the link here?

**Comment by sayakpaul** [comment]
Of course. Here you go: https://github.com/sayakpaul/SimCLR-in-TensorFlow-2.

**Comment by chentingpc** [comment]
added!

**Comment by sayakpaul** [comment]
Thank you!
