### ISSUE TITLE
One-class classification

### ISSUE THREAD

**Issue by sehyungp92** [google-research/simclr#33]
Firstly, many thanks for sharing a very interesting piece of research. 

I was just wondering if such a representation learning framework may also prove to be effective for one-class classification (or anomaly / novelty detection) tasks. One very simple setting may involve just training a one-class SVDD (Ruff et al. 2018) on top of a frozen base network (trained on, say, ImageNet). It would be great to hear your views!

Kind regards,
Se

**Comment by chentingpc** [comment]
We didn't explore this setup but I think good representations could help here.
