### ISSUE TITLE
Do released model include fine-tuning stage?

### ISSUE THREAD

**Issue by andrewliao11** [google-research/simclr#34]
Hi 
Thanks for releasing the code and the weights. Just a quick question, are the weight released [here](https://github.com/google-research/simclr#pre-trained-models) before-finetune or after-finetune?

Best, 
Andrew

**Comment by chentingpc** [comment]
it is before fine-tuning. well, actually we will release a few more weights (on SimCLRv2), which will include also fine-tuning weights.

**Comment by andrewliao11** [comment]
Got it thanks!
