### ISSUE TITLE
Questions about the dataset

### ISSUE THREAD

**Issue by xiaoyi-st** [google-research/simclr#35]
How to set up your own data set for training，such as  jpg data set?

**Comment by chentingpc** [comment]
We use tensorflow datasets, you can see how to add a dataset here: https://www.tensorflow.org/datasets/add_dataset

**Comment by xiaoyi-st** [comment]
This can only add the data downloaded from the Internet, can not add your own data set？

**Comment by xiaoyi-st** [comment]
Why did the program automatically select the original data set when I tested the CARIF10 data set




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ting Chen"<notifications@github.com&gt;; 
发送时间: 2020年6月19日(星期五) 上午10:47
收件人: "google-research/simclr"<simclr@noreply.github.com&gt;; 
抄送: "R"<1120922880@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [google-research/simclr] Questions about the dataset (#35)





 
We use tensorflow datasets, you can see how to add a dataset here:&nbsp;https://www.tensorflow.org/datasets/add_dataset

**Comment by chentingpc** [comment]
you can add the data downloaded from the internet using the link i attached above (just make local changes).

You should change the FLAGS to use CIFAR10 or other dataset.
