### ISSUE TITLE
Basic question on my understanding

### ISSUE THREAD

**Issue by pradeepram80** [google-research/simclr#36]
Hi,
Had a question on the underlying paper itself. Not sure where else I could ask.
-  What is the basis for assuming the crops of the same image should form a positive semantically related pair vs crops from different images are not semantically related?
        -   For example, two crops of the same image could have nothing semantically in common. Similarly crops of two different images could have the same semantics. Wouldnt this affect the learning process? This would be especially true if object of interest is localized in one small part of the image.

**Comment by chentingpc** [comment]
you can send it via email in the future, as the github issues are mainly for the code. What you said here is a valid concern, and it also depends on how you crop the image. In practice, the random crops using our implementation are quite correlated, see some samples in our slide here: https://docs.google.com/presentation/d/1ccddJFD_j3p3h0TCqSV9ajSi2y1yOfh0-lJoK29ircs/edit#slide=id.g88de1f3f96_5_717
