### ISSUE TITLE
Why does the paper choose 0.1 as temperature value?

### ISSUE THREAD

**Issue by Some-random** [google-research/simclr#37]
In the paper the explanation on temperature is **l2 normalization along with temperature effectively weights different examples, and an appropriate temperature can help the model learn from hard negatives**. But I can't really understand how adding temperature achieves 'learning  from hard negatives'... Also, looking at Table 5, it seems like choosing 0.1 is significantly better than choosing temperature larger/ smaller than 0.1. I'm also wondering how that happened...

**Comment by chentingpc** [comment]
you can see the negative weighting in the gradient in Table 2. That's our interpretation, and there may be others.

**Comment by Some-random** [comment]
Thanks @chentingpc for the quick reply! I did read through the gradient computation in Table 2, but I still can't understand its relationship to 'hard negatives'... I was expecting the loss function will do something differently for 'easy negatives' and 'hard negatives'

**Comment by chentingpc** [comment]
I guess you can also see it in the loss instead of the gradient, you can write the loss (roughly) as -score_i/tau + logsumexp(sum score_j / tau). with a smaller tau, logsumexp will approximate more max, which picks up the hardest one, but larger tau it will be more smooth.
