### ISSUE TITLE
Running error - could you please look into this?

### ISSUE THREAD

**Issue by HelenaELiu** [google-research/simclr#39]
I get an error when I run this command:

python run.py --mode=train_then_eval --train_mode=finetune \
  --fine_tune_after_block=4 --zero_init_logits_layer=True \
  --variable_schema='(?!global_step|(?:.*/|^)Momentum|head)' \
  --global_bn=False --optimizer=momentum --learning_rate=0.1 --weight_decay=0.0 \
  --train_epochs=2 --train_batch_size=512 --warmup_epochs=0 \
  --dataset=cifar10 --image_size=32 --eval_split=test --resnet_depth=18 \
  --checkpoint=/tmp/simclr_test --model_dir=/tmp/simclr_test_ft --use_tpu=False

(Note: I changed train_epochs to 2 so that it would run quickly.)

The error is:

ValueError: Shape of variable module/head_supervised/linear_layer/dense/kernel:0 ((512, 10)) doesn't match with shape of tensor head_supervised/linear_layer/dense/kernel ([128, 10]) from checkpoint reader.

I am using TensorFlow 1.15.2. While I was trying to figure out this error, I downloaded your old code prior to the update 5 days ago and found that it runs well. Could you please look into this issue? Thank you very much!

**Comment by charlielito** [comment]
I think the image size should be 224

**Comment by chentingpc** [comment]
Thanks for reporting the bug. It is not due to the image size. It is due to the `ft_proj_selector`, and you should be able to fix it by adding a flag `--ft_proj_selector=0`. Please let me know if it fixes it.

**Comment by HelenaELiu** [comment]
Thank you so much, it works now. I also have another question - the results in the .json file look like this:

{"contrast_loss": 0.0, "contrastive_top_1_accuracy": 1.0, "contrastive_top_5_accuracy": 1.0, "label_top_1_accuracy": 0.8755999803543091, "label_top_5_accuracy": 0.9965, "loss": 0.3648136854171753, "regularization_loss": 0.0, "global_step": 977.0}

Is the contrastive accuracy supposed to be 1.0? Isn't that too high?

Thank you very much!

**Comment by chentingpc** [comment]
is this during the linear eval / fine-tuning? if so, this metric is not meaningful due to https://github.com/google-research/simclr/blob/244e7128004c5fd3c7805cf3135c79baa6c3bb96/model.py#L81.

**Comment by HelenaELiu** [comment]
It is for the linear eval, thank you so much! I got it. I'm going to close this thread because you answered my questions.
