### ISSUE TITLE
How to tap the features after encoder

### ISSUE THREAD

**Issue by rakshith291** [google-research/simclr#40]
I have obtained checkpoints after training simCLR V1 with cifar 10 data. Now how can I use these checkpoint to tap the features(representation) after encoder.

**Comment by chentingpc** [comment]
You can fine-tuning the model (either just the final linear layer, or the entire network) with labels. Please see the readme for fine-tuning scripts.

**Comment by rakshith291** [comment]
> You can fine-tuning the model (either just the final linear layer, or the entire network) with labels. Please see the readme for fine-tuning scripts.

Thanks for the reply.
Correct me if I'm wrong when I pertain SIMCLR V1
Using the hyper parameters given in Read me.

I'm training resnet 50 + non projection head(MLP) right?
I believe there is no use of labels or any supervised learning involved.

So if I want to fine tune, linear layer & supervised learning comes into consideration ??
My understanding is correct??

**Comment by chentingpc** [comment]
you're right. labels are only used during the fine-tuning.
