### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by rakshith291** [google-research/simclr#41]
I have checkpoints of SimCLR V1
I want to input an image and I want to obtain features representation from encoder (2048D) as output.

Can you please guide me regarding this

I figured out , my output tensor will be 'base_model/final_avg_pool:0',
But couldn't find the input tensor name. It was quite complicated to understand from graph.

**Comment by chentingpc** [comment]
are you using hub module? it should be quite straight forward, and an example is given below:
```
module = hub.Module(hub_module_path, trainable=False)
fake_image = tf.zeros([1, 224, 224, 3])
output_dict = module(inputs=fake_image, signature="default", as_dict=True)
```
The `output_dict` contains a set of tensors that you can use, such as the following
```
{'block_group4': <tf.Tensor 'module_apply_default/base_model/block_group4:0' shape=(1, 7, 7, 4096) dtype=float32>,
 'final_avg_pool': <tf.Tensor 'module_apply_default/base_model/final_avg_pool:0' shape=(1, 4096) dtype=float32>,
 'block_group2': <tf.Tensor 'module_apply_default/base_model/block_group2:0' shape=(1, 28, 28, 1024) dtype=float32>,
 'block_group3': <tf.Tensor 'module_apply_default/base_model/block_group3:0' shape=(1, 14, 14, 2048) dtype=float32>,
 'block_group1': <tf.Tensor 'module_apply_default/base_model/block_group1:0' shape=(1, 56, 56, 512) dtype=float32>,
 'default': <tf.Tensor 'module_apply_default/head_contrastive/Relu:0' shape=(1, 4096) dtype=float32>,
 'logits_sup': <tf.Tensor 'module_apply_default/head_supervised/linear_layer/linear_layer_out:0' shape=(1, 1000) dtype=float32>,
 'initial_max_pool': <tf.Tensor 'module_apply_default/base_model/initial_max_pool:0' shape=(1, 56, 56, 128) dtype=float32>,
 'initial_conv': <tf.Tensor 'module_apply_default/base_model/initial_conv:0' shape=(1, 112, 112, 128) dtype=float32>}
```

**Comment by rakshith291** [comment]
> 
> 
> are you using hub module? it should be quite straight forward, and an example is given below:
> 
> ```
> module = hub.Module(hub_module_path, trainable=False)
> fake_image = tf.zeros([1, 224, 224, 3])
> output_dict = module(inputs=fake_image, signature="default", as_dict=True)
> ```
> 
> The `output_dict` contains a set of tensors that you can use, such as the following
> 
> ```
> {'block_group4': <tf.Tensor 'module_apply_default/base_model/block_group4:0' shape=(1, 7, 7, 4096) dtype=float32>,
>  'final_avg_pool': <tf.Tensor 'module_apply_default/base_model/final_avg_pool:0' shape=(1, 4096) dtype=float32>,
>  'block_group2': <tf.Tensor 'module_apply_default/base_model/block_group2:0' shape=(1, 28, 28, 1024) dtype=float32>,
>  'block_group3': <tf.Tensor 'module_apply_default/base_model/block_group3:0' shape=(1, 14, 14, 2048) dtype=float32>,
>  'block_group1': <tf.Tensor 'module_apply_default/base_model/block_group1:0' shape=(1, 56, 56, 512) dtype=float32>,
>  'default': <tf.Tensor 'module_apply_default/head_contrastive/Relu:0' shape=(1, 4096) dtype=float32>,
>  'logits_sup': <tf.Tensor 'module_apply_default/head_supervised/linear_layer/linear_layer_out:0' shape=(1, 1000) dtype=float32>,
>  'initial_max_pool': <tf.Tensor 'module_apply_default/base_model/initial_max_pool:0' shape=(1, 56, 56, 128) dtype=float32>,
>  'initial_conv': <tf.Tensor 'module_apply_default/base_model/initial_conv:0' shape=(1, 112, 112, 128) dtype=float32>}
> ```

Thanks , Now I'm able to obtain feature representation.
In order to generate TF hub module , can I call it at the end of pretrain mode as well once I obtain checkpoint ?

**Comment by chentingpc** [comment]
If you run evaluation, it will automatically generate the tf hub module for you. see https://github.com/google-research/simclr/blob/244e7128004c5fd3c7805cf3135c79baa6c3bb96/run.py#L341
