### ISSUE TITLE
Questions about the mod_DIR path in Run.py

### ISSUE THREAD

**Issue by xiaoyi-st** [google-research/simclr#44]
Hello, I'm here to disturb you again. When I was training your simclr model, I saw in your readme that if you use the imagenet2012 dataset, mod_dir=None, and when training the ciarf10 dataset, mod_dir=/tmp/simclr_test. Does this mod_dir refer to the model storage location? Or is the model automatically selected when training different data sets?

**Comment by chentingpc** [comment]
`model_dir` is the place for saving model checkpoint. You should set it manually depending on whether you're running locally or using cloud (storage). it doesn't matter which dataset you're using.
