### ISSUE TITLE
Using a single GPU to train the carif10 data set fails to start

### ISSUE THREAD

**Issue by xiaoyi-st** [google-research/simclr#45]
Hello, when I used the single GPU to train the caifr10 data set, the following prompt appeared: The system prompts to skip this training.
The system prompts as follows:
INFO:tensorflow:_TPUContext: eval_on_tpu True
I0627 17:39:39.536073 139766252832576 tpu_context.py:209] _TPUContext: eval_on_tpu True
WARNING:tensorflow:eval_on_tpu ignored because use_tpu is False.
W0627 17:39:39.536876 139766252832576 tpu_context.py:211] eval_on_tpu ignored because use_tpu is False.
INFO:tensorflow:Skipping training since max_steps has already saved.
I0627 17:39:39.541100 139766252832576 estimator.py:360] Skipping training since max_steps has already saved.
INFO:tensorflow:training_loop marked as finished
I0627 17:39:39.541271 139766252832576 error_handling.py:96] training_loop marked as finished

**Comment by chentingpc** [comment]
it seems you're continuing training from a checkpoint where the global_step is equal to max steps so it is stoped automatically. You can set the model_dir to new location so it won't automatically continue training from existing checkpoint. Or you can set `--checkpoint` explicit and exclude loading `global_step` so it will be reset to zero.

**Comment by xiaoyi-st** [comment]
Thank you very much for your guidance！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ting Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月27日(星期六) 晚上11:11
收件人:&nbsp;"google-research/simclr"<simclr@noreply.github.com&gt;;
抄送:&nbsp;"R"<1120922880@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [google-research/simclr] Using a single GPU to train the carif10 data set fails to start (#45)





 
it seems you're continuing training from a checkpoint where the global_step is equal to max steps so it is stoped automatically. You can set the model_dir to new location so it won't automatically continue training from existing checkpoint. Or you can set --checkpoint explicit and exclude loading global_step so it will be reset to zero.
