### ISSUE TITLE
Can SimCLR apply to NLP task?

### ISSUE THREAD

**Issue by guotong1988** [google-research/simclr#46]
Has someone did it? How is the performance on NLP task?

Thank you!

**Comment by chentingpc** [comment]
We haven't tried it for NLP tasks, and I am not aware of work applying SimCLR to NLP task. It can definitely be applied to NLP, but it is hard to say if it will do better than BERT. You're encouraged to try!

**Comment by guotong1988** [comment]
SimCLR + BERT > BERT ?

**Comment by guotong1988** [comment]
SimCLR + small dataset = BERT + big dataset ?

**Comment by guotong1988** [comment]
Oh, SimCLR is for pre-training. I misunderstand SimCLR and UDA.
