### ISSUE TITLE
SimCLR v2 full implementation?

### ISSUE THREAD

**Issue by jlindsey15** [google-research/simclr#54]
Hi!  As far as I can tell, this implementation doesn't contain the MOCO-style memory mechanism that is mentioned in the SimCLR v2 paper.  Am I missing something?  If not, will the full SimCLR v2 implementation be released, and if so, when?

**Comment by chentingpc** [comment]
The memory mechanism would make the code more complicated as it will add EMA network, memory buffer, etc. We'd rather keep this code base simple for now.

**Comment by bryanyzhu** [comment]
Is it possible to release the full implementation in another branch? Adding memory may not provide a significant performance boost, but it is great to have it for analysis and fair comparison. Thank you.
