### ISSUE TITLE
Regarding Table 1 in paper SimCLR V2

### ISSUE THREAD

**Issue by Some-random** [google-research/simclr#55]
I'm trying to understand the column "F-T (100%)" in Table 1. It seems like with the same network structure (152 depth, 3* width, SK), finetuning with 100% of data is way better than training from scratch.

 Does that mean using the same amount of data and the same structure, pre-training with SimCLR V2 gives consistent and significant boost compared to training from scratch? And if so, why is that?

**Comment by chentingpc** [comment]
Pretrained and fine-tuned (100%) models are better than supervised models that use *standard* training from scratch. By using good augmentation strategy and other regularization techniques, training from scratch can also be improved.

**Comment by Some-random** [comment]
Thanks for your explanation! I'm just wondering do you have the results with/ without pre-trained SimCLR v2 model under the same augmentation condition? I'm also worried augmentation in fine-tuning stage might reduce the benefit SimCLR v2 pre-training brings.

**Comment by chentingpc** [comment]
we do not use augmentations other than random crop and flip during fine-tuning. for supervised models, using the SimCLR augmentation provides some benefits (e.g., see Table B.3 in https://arxiv.org/pdf/2002.05709.pdf), but it is not as big as the benefits from unsupervised pretraining.
