### ISSUE TITLE
error when using predict, Could you please look into this 

### ISSUE THREAD

**Issue by ambekarsameer96** [google-research/simclr#61]
Hi @chentingpc when I tried to use estimator predict function in run.py file in perform_evaluation() function as shown in the snippet below - Can you please let me know why predict doesn't seem to work. 

```
def perform_evaluation(estimator, input_fn, eval_steps, model, num_classes,
                       checkpoint_path=None):
  """Perform evaluation.

  Args:
    estimator: TPUEstimator instance.
    input_fn: Input function for estimator.
    eval_steps: Number of steps for evaluation.
    model: Instance of transfer_learning.models.Model.
    num_classes: Number of classes to build model for.
    checkpoint_path: Path of checkpoint to evaluate.

  Returns:
    result: A Dict of metrics and their values.
  """
  if not checkpoint_path:
    checkpoint_path = estimator.latest_checkpoint()
  result = estimator.evaluate(
      input_fn, eval_steps, checkpoint_path=checkpoint_path,
      name=FLAGS.eval_name)

  #predict added here
  preds = estimator.predict(input_fn, eval_steps, checkpoint_path=checkpoint_path)

  #print 
  print('-------------------------Predictions ', preds)
  for value in preds:
    print(value)
  
  # Record results as JSON.
  result_json_path = os.path.join(FLAGS.model_dir, 'result.json')
  with tf.io.gfile.GFile(result_json_path, 'w') as f:
    json.dump({k: float(v) for k, v in result.items()}, f)
  result_json_path = os.path.join(
      FLAGS.model_dir, 'result_%d.json'%result['global_step'])
  with tf.io.gfile.GFile(result_json_path, 'w') as f:
    json.dump({k: float(v) for k, v in result.items()}, f)
  flag_json_path = os.path.join(FLAGS.model_dir, 'flags.json')
  with tf.io.gfile.GFile(flag_json_path, 'w') as f:
    json.dump(FLAGS.flag_values_dict(), f)
```

I encountered the following error - 

-------------------------Predictions  <generator object TPUEstimator.predict at 0x7fc925bb27d8>
I0719 09:00:28.419117 140503382996864 dataset_builder.py:458] Constructing tf.data.Dataset for split test, from /root/tensorflow_datasets/cifar10/3.0.0
INFO:tensorflow:prediction_loop marked as finished
I0719 09:00:28.528095 140503382996864 error_handling.py:115] prediction_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0719 09:00:28.528371 140503382996864 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "run.py", line 442, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run.py", line 437, in main
    num_classes=num_classes)
  File "run.py", line 332, in perform_evaluation
    for value in preds:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3126, in predict
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3120, in predict
    yield_single_examples=yield_single_examples):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 611, in predict
    input_fn, ModeKeys.PREDICT)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1014, in _get_features_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in _call_input_fn
    return input_fn(**kwargs)
  File "/content/simclr/data.py", line 144, in _input_fn
    dataset = dataset.batch(params['batch_size'], drop_remainder=is_training)
KeyError: 'batch_size'

PS: I got this error when I used custom dataset as well as when I used Cifar dataset while the fine-tuning process.

**Comment by chentingpc** [comment]
It seems for some reason batch size is not set correctly for evaluation. A dirty hack is to set it manually in File "/content/simclr/data.py", line 144 as pointed out by the error log. This may be due to a misconfigure of your custom dataset, but if you use datasets from [tfds](https://www.tensorflow.org/datasets/catalog/overview), this problem should disappear.

**Comment by ambekarsameer96** [comment]
I did try this hack earlier itself but after that it said on this line 

 obj_lib.add_supervised_loss(
          labels=labels['labels'],
          logits=logits_sup,
          weights=labels['mask'])

the error was : labels['labels'] :  'NoneType' object is not subscriptable

I have encountered this error when I used you code for both Cifar (used as mention in your repo) and also for my custom data.

**Comment by ambekarsameer96** [comment]
@chentingpc  Thank you for your quick response. 
Also how do I use multi-TPUs to train? 
It works fine for single TPU, but when I initialize environment variable with 

export TPU_NAME=tpu1, tpu2  

It doesn't execute. When I looked up documentation of 
tf.distribute.cluster_resolver.TPUClusterResolver(
          FLAGS.tpu_name, zone=FLAGS.tpu_zone, project=FLAGS.gcp_project)
(which has been used in your run.py )  at the link - 
https://www.tensorflow.org/api_docs/python/tf/distribute/cluster_resolver/TPUClusterResolver#args_1

For the argument 'tpu' it says "In the future, this may also support a list of strings when multiple Cloud TPUs are used."

Can you please let me know how can I use multi-TPUs for training because it looks like this cluster command is only for single TPU. (correct me if I am wrong)

**Comment by chentingpc** [comment]
It should work out of box for cifar10 dataset, not sure how you got the error there. you may git clone a clean codebase and see if the problem persists.

Re multi-TPU, you can simply change the tpu_type and it would distribute automatically, see https://cloud.google.com/tpu/docs/types-zones.

**Comment by ambekarsameer96** [comment]
Hi @chentingpc , I did try again on Cifar dataset but got the same error. 
Please check the colab notebook where you can see the error on Cifar dataset when predict is used. You can also reproduce the error on colab since I have added detailed instructions on how to reproduce it. 
Colab link - https://colab.research.google.com/drive/1rkxJB7F-LCJDlV1UHpGDCaC_wQccoOSZ?usp=sharing

Let me know if you are not able to reproduce it. Please refer to the comments to reproduce the error.

**Comment by ambekarsameer96** [comment]
Re Multi TPU I will try it. Thank you.

Also when I used parameters similar to Imagenet parameters mentioned in your readme file on one single Cloud TPU v2 (8 cores)  for a batch size of 512 images, the number of examples per second is however very less. 
tt varies between 30-40 examples per second. Due to this the training time is very high. Can you please let me know why the number of examples is so less and how can I increase it.

**Comment by chentingpc** [comment]
I am running your colab and it doesn't given the error you encountered. Noted that my run didn't change any files in this repo, so it is possible the errors you got may be due some changes introduced.

**Comment by ambekarsameer96** [comment]
Thanks for taking a look at it. Appreciate your patience.  
It's strange that you didn't get the error. Did you add the 'predict' function in the run.py file as mentioned in one of the cells on colab?

**Comment by chentingpc** [comment]
I didn't add the `estimator.predict`. have you tried remove `estimator.evaluate` when you added predict?

**Comment by ambekarsameer96** [comment]
Although I removed estimator.evaluate it didnt work. 
Can you please add this in run.py and check if it works - 
``#predict function
  preds = estimator.predict(input_fn, eval_steps, checkpoint_path=checkpoint_path)

  #print 
  print('-------------------------Predictions ', preds)
  for value in preds:
    print(value)
``

**Comment by fazlekarim** [comment]
I am having the same issue. and its really frustrating.

**Comment by fazlekarim** [comment]
Hi,

To fix the batch_size error, add predict_batch_size into the estimator (I created a flag for predict_batch_size)

```
estimator = tf.estimator.tpu.TPUEstimator(
      model_lib.build_model_fn(model, num_classes, num_train_examples),
      config=run_config,
      train_batch_size=FLAGS.train_batch_size,
      eval_batch_size=FLAGS.eval_batch_size,
      predict_batch_size=FLAGS.predict_batch_size,
      use_tpu=FLAGS.use_tpu)
```

Then you will receive a non type error about the loss function in your model file. I believe (please correct me @chentingpc ), we do not need the loss information for predict. So I added an if statement right before obj_lib.add_supervised_loss:
```
      if is_training:
          obj_lib.add_supervised_loss(
              labels=labels['labels'],
              logits=logits_sup,
              weights=labels['mask'])
```

Finally, you will need to add conditions when the mode is tf.estimator.ModeKeys.PREDICT.
So in the else loop, after if_training: 
```
      if is_predict:
          predictions = logits_sup
          _, top_5 = tf.nn.top_k(predictions, k=1)
          predictions = {
              'top_1': tf.argmax(predictions, axis=1),
              'top_5': top_5,
              'probabilities': tf.nn.softmax(predictions),
              'logits': predictions,
          }
          return tf.estimator.tpu.TPUEstimatorSpec(mode, predictions=predictions)
      else:

          def metric_fn(logits_sup, labels_sup, logits_con, labels_con, mask,
                        **kws):
            """Inner metric function."""

            metrics = {k: tf.metrics.mean(v, weights=mask)
                       for k, v in kws.items()}
            metrics['label_top_1_accuracy'] = tf.metrics.accuracy(
                tf.argmax(labels_sup, 1), tf.argmax(logits_sup, axis=1),
                weights=mask)
            if not (FLAGS.dataset == "siim_dataset"):
                metrics['label_top_5_accuracy'] = tf.metrics.recall_at_k(
                    tf.argmax(labels_sup, 1), logits_sup, k=5, weights=mask)
            metrics['contrastive_top_1_accuracy'] = tf.metrics.accuracy(
                tf.argmax(labels_con, 1), tf.argmax(logits_con, axis=1),
                weights=mask)
            if not (FLAGS.dataset == "siim_dataset"):
                metrics['contrastive_top_5_accuracy'] = tf.metrics.recall_at_k(
                    tf.argmax(labels_con, 1), logits_con, k=5, weights=mask)
            return metrics


          metrics = {
              'logits_sup': logits_sup,
              'labels_sup': labels['labels'],
              'logits_con': logits_con,
              'labels_con': labels_con,
              'mask': labels['mask'],
              'contrast_loss': tf.fill((params['batch_size'],), contrast_loss),
              'regularization_loss': tf.fill((params['batch_size'],),
                                             tf.losses.get_regularization_loss()),
          }

          return tf.estimator.tpu.TPUEstimatorSpec(
              mode=mode,
              loss=loss,
              eval_metrics=(metric_fn, metrics),
              scaffold_fn=None)
```

I think that should fix your issue.

**Comment by chentingpc** [comment]
It seems you want to get the predicted results instead of just the final metrics? If that's the case, another possibility is to use session instead of estimator. You can even do this in the colab (with GPU on to speedup), see this example: https://github.com/google-research/simclr/blob/master/colabs/load_and_inference.ipynb
