### ISSUE TITLE
can you please kindly provide the pretrained model on imagenet?

### ISSUE THREAD

**Issue by realbns2008** [google-research/simclr#67]
HI,
   I'm very interested in using the pertained model to do some specific task.
   Due to it need use very large computing resource to pretrain the model on imagenet, it is difficult for me to reproduce the model from imagenet. 
   Can you please kindly offered the pretrained model on imagenet?

many thanks 👍

**Comment by chentingpc** [comment]
please see the readme file for access the pretrained models. there are 3 models for simclr v1, and 65 models for simclr v2 available.

**Comment by realbns2008** [comment]
Wow, that's really nice :)
Thanks a lot @chentingpc

**Comment by deepankarvarma** [comment]
@realbns2008 Did you do the downstream task through transfer learning, if yes can you please share the notebook ?
