### ISSUE TITLE
The training result model is repeated and the latest running result cannot be saved

### ISSUE THREAD

**Issue by xiaoyi-st** [google-research/simclr#69]
Hi,I met a problem and urgently need your help
The training result model is repeated, the latest running result cannot be saved, or it may not be running, the situation is as follows：INFO:tensorflow:Saving 'checkpoint_path' summary for global step 314961: /media/disk2/xieting/new_simclr/simclr-master/RESULT/model.ckpt-314961
I0730 14:55:42.147005 139628833138496 estimator.py:2109] Saving 'checkpoint_path' summary for global step 314961: /media/disk2/xieting/new_simclr/simclr-master/RESULT/model.ckpt-314961
INFO:tensorflow:evaluation_loop marked as finished
I0730 14:55:42.147590 139628833138496 error_handling.py:101] evaluation_loop marked as finished

**Comment by chentingpc** [comment]
I'm guessing that changing the `checkpoint_path` to new directory could solve your problem. Or deleting checkpoints in the existing `checkpoint_path`.

**Comment by xiaoyi-st** [comment]
However, I changed the Checkpoint_Path and the running time was completely different from the last time. The parameters and data I used and the network results did not change.

**Comment by chentingpc** [comment]
paste some results here? i'm not sure what exactly is going on

**Comment by chentingpc** [comment]
close the issue due to no additional activity
