### ISSUE TITLE
Could you please kindly provide the self-distilled model(ResNet152-3x-sk1) for us

### ISSUE THREAD

**Issue by YFWDZWS** [google-research/simclr#70]
Hi:
    I am a reasearcher about self-supervised learning and I really appriaciate your work about SimCLR v2, and could you kindly provide the self-distilled model(ResNet152-3x-sk1) for us, thank you so much!

**Comment by YFWDZWS** [comment]
Also the ResNet-50 which is distilled from big model (like Res 152-3x-sk1)

**Comment by chentingpc** [comment]
we are considering oss distilled models, but it could take a few days/weeks. will notify here once they're available.

**Comment by chentingpc** [comment]
The distilled model checkpoints have been released at [gs://simclr-checkpoints/simclrv2](https://console.cloud.google.com/storage/browser/simclr-checkpoints/simclrv2/). Let me know if there's any issues.

**Comment by YFWDZWS** [comment]
Thank you so much for your update！

Best
Yifei Wu

Ting Chen <notifications@github.com>于2020年8月19日 周三上午1:43写道：
