### ISSUE TITLE
Stage 3: Model Distillation

### ISSUE THREAD

**Issue by sp7412** [google-research/simclr#71]
Is there a colab notebook for the model distillation stage?

**Comment by YFWDZWS** [comment]
+1

**Comment by chentingpc** [comment]
The colab for demonstrating distillation / self-training are now available in here: https://github.com/google-research/simclr/blob/master/colabs/distillation_self_training.ipynb

**Comment by YFWDZWS** [comment]
> The colab for demonstrating distillation / self-training is now available in here: https://github.com/google-research/simclr/blob/master/colabs/distillation_self_training.ipynb

Thank you so much for your update!
