### ISSUE TITLE
Hyper-parameters for Transfer Learning

### ISSUE THREAD

**Issue by frank-xwang** [google-research/simclr#72]
Hi, thanks for your excellent work. Is it possible for us to know the detailed hyper-parameters for each transfer learning datasets? In your paper, you mentioned using grid search to select the best hyperparameters, but did not give the final choice. It may be hard for us to reproduce your results without these information. The hyper-params for ResNer 50 1x will be good enough. Thanks.

**Comment by chentingpc** [comment]
@simonster conducted transfer experiments and may have more to say on this.

**Comment by deepankarvarma** [comment]
by any case can you share the transfer learning notebook
