### ISSUE TITLE
Use the pre-trained models in TF v2

### ISSUE THREAD

**Issue by tarunn2799** [google-research/simclr#80]
Hey @chentingpc, thanks for the wide variety of pre-trained models for SimCLR. I noticed that the models provide all come in TensorFlow V1 Hub format. How do I go about loading these models in TF v2? 

Is there some form of conversion I can do? Please help me out with this. Thank you.

**Comment by chentingpc** [comment]
We do not have the converter or converted models for TF2 yet, but there may be some updates in the near future. Stay tuned!
