### ISSUE TITLE
Support training from scratch?

### ISSUE THREAD

**Issue by mushan09** [google-research/simclr#83]
@chentingpc  I want to compare  the improvement between training from scratch and simCLR v2 in my datasets, but I didn’t find out how to configure training from scratch.

**Comment by chentingpc** [comment]
Do you mean unsupervised pretraining from scratch? If so, the instruction is on the readme page

**Comment by mushan09** [comment]
> Do you mean unsupervised pretraining from scratch? If so, the instruction is on the readme page

I'm sorry I didn't express it clearly, what I want to say is supervised learning.
What I want to do is to compare the improvement of simCLR v2 by controlling the only variable on my datasets, using your code.

**Comment by chentingpc** [comment]
You can set `--train_mode=finetune` to do supervised learning with this codebase. The example command below is modified from fine-tuning command in ReadMe.

```
python run.py --mode=train_then_eval --train_mode=finetune \
  --fine_tune_after_block=-1 --zero_init_logits_layer=False \
  --global_bn=False --optimizer=momentum --learning_rate=0.1 --weight_decay=1e-4 \
  --train_epochs=100 --train_batch_size=128 --warmup_epochs=0 \
  --dataset=cifar10 --image_size=32 --eval_split=test --resnet_depth=18 \
  --model_dir=/tmp/sup_test --use_tpu=False
```

**Comment by mushan09** [comment]
Thank you so much! It works, and I also removed the projection_head for supervised learning, I think supervised learning generally does not add projection_head. 

The best result I got based on hyperparameter search is blow. 
model| lr | weight_decay | warmup_epoch | batch_size | cifar_10_top1
-- | -- | -- | -- | -- | --
res18 | 0.5 | 0.0001 | 0 | 512 | 0.9378

Compared with this work(https://github.com/davidcpage/cifar10-fast) I saw before, the result is a bit lower, I don't know where the problem is. If you are free, can you give me some tips? 
Thanks again!

**Comment by chentingpc** [comment]
Oh our cifar network was simply modified from imagenet resnet by changing the conv stem (see [here](https://github.com/google-research/simclr/blob/81e63a27be8b400a268cd4e1710af7590d172a36/resnet.py#L567)), and this may not be the most cost efficient network architecture for cifar. If you want to get the best cifar performance, you may need to modify the architecture.

**Comment by mushan09** [comment]
Thanks a lot.
