### ISSUE TITLE
How to use multi-GPUs?

### ISSUE THREAD

**Issue by Tae39** [google-research/simclr#85]
Sorry to bother you again. I have read the statement in which you said that the code does not support multi-GPUs. Is there any suggestion or reference for using multi-GPUs? Look forward to your kind advice and thank you so much once again.

**Comment by chentingpc** [comment]
unfortunately I'm also not familiar with that personally. You could search around to see how to use multi-gpus with estimator. but a potentially good news is that some of us are working on tf2 of the implementation and will be released in near future, which should support the multi-gpu setup.

**Comment by Tae39** [comment]
wow, that's a good news. Thank you! : )
