### ISSUE TITLE
Is tpu_cross_replica_concat differentiable

### ISSUE THREAD

**Issue by ruotianluo** [google-research/simclr#87]
I am looking at pytorch replications and your code.
Due to lack of expertise in tensorflow, I am curious if your tpu_cross_replica_concat(https://github.com/google-research/simclr/blob/81e63a27be8b400a268cd4e1710af7590d172a36/objective.py#L61) will pass the grad to hidden1.

**Comment by chentingpc** [comment]
yes it will
