### ISSUE TITLE
Tensorflow to PyTorch checkpoint conversion, mismatch of number of layers for SimCLRv2.

### ISSUE THREAD

**Issue by sahiljuneja** [google-research/simclr#88]
Hi,

I was initially working with the Checkpoints provided corresponding to SimCLR (v1) and I used this repo https://github.com/tonylins/simclr-converter to convert those to PyTorch. Managed to do so without issue.

However, I am now trying to utilize the **v2** checkpoints, specifically the `Pretrained SimCLRv2 models (with linear eval head)` ones with sk=0.

I have tried with the checkpoints corresponding to ResNet50 and ResNet152 and both threw an error at the time of conversion. I looked at the layers in ResNet50 checkpoint for SimCLR (v1) and printed those out, here are the first three -

> torch.Size([64, 3, 7, 7])
> torch.Size([256, 64, 1, 1])
> torch.Size([64, 64, 1, 1])

When I print out the first **six** corresponding to the downloaded checkpoints for SimCLR (v2) -

> torch.Size([64, 3, 7, 7])
> torch.Size([64, 3, 7, 7])
> torch.Size([256, 64, 1, 1])
> torch.Size([256, 64, 1, 1])
> torch.Size([64, 64, 1, 1])
> torch.Size([64, 64, 1, 1])

The layers are doubled for the same ResNet50.

Based on https://github.com/google-research/simclr/blob/master/resnet.py I am unable to currently identify why this would be the case. Could you help clarify this?

- Is this expected for SimCLRv2?
- If yes, then where in the TF code does this happen so that I can look into adjusting this for the PyTorch converter?

Thank you!

**Comment by chentingpc** [comment]
I am guessing that's due to the existence of ema network (which can be ignored). You can filter weights by `base_model` and `ema_model` and only use those under `base_model/*`.

**Comment by sahiljuneja** [comment]
Thanks for the response. I looked into the variables of the model (using `tf.train.list_variables()`) for both checkpoints.

Here are the initial conv2d layers that it shows.

For ResNet50 (SimCLR v1) -

> base_model/conv2d/kernel
base_model/conv2d_1/kernel
base_model/conv2d_10/kernel

For ResNet50 (SimCLR v2) -

> base_model/conv2d/kernel
base_model/conv2d/kernel/Momentum
base_model/conv2d_1/kernel
base_model/conv2d_1/kernel/Momentum
base_model/conv2d_10/kernel
base_model/conv2d_10/kernel/Momentum

Those `/Momentum` variables are what's present additionally. 

Can those be ignored as well for the conversion? Or will that have a significant impact?

**Comment by chentingpc** [comment]
Yes. The `/Momentum` variables are used for the Momentum optimizer only, and it can certainly be removed.

**Comment by sahiljuneja** [comment]
Thanks for the confirmation! Was able to convert it without much issue.

**Comment by EvgeniaAR** [comment]
@sahiljuneja I am trying to do the exact same thing and having issues. Could you maybe share your code how to fix the SimCLR1 conversion code to work with SimCLRv2? I only know pytorch and have trouble with tensorflow.

**Comment by sahiljuneja** [comment]
@EvgeniaAR 

Sure, it'ts a very small fix. I haven't added the code to GitHub yet, but essentially replace the code line [here](https://github.com/tonylins/simclr-converter/blob/master/convert.py#L30) with -

```
conv_keys = [k for k in sd.keys() if k.split('/')[1].split('_')[0] == 'conv2d' and "Momentum" not in k]
```

The `and "Momentum" not in k` part will ignore all conv layers that have the form - `base_model/conv2d_1/kernel/Momentum`.

Hope this helps!

**Comment by EvgeniaAR** [comment]
Awesome!!! Thank you so much @sahiljuneja, it works! :) :)

**Comment by chentingpc** [comment]
very nice @sahiljuneja ! it seems this code change is compatible for v1 checkpoints? you may also want to submit this as pull request directly for the converter's code.

**Comment by sahiljuneja** [comment]
> it seems this code change is compatible for v1 checkpoints?

I believe so. I will have to test again, just in case. I think I tested it once and it worked without issue.

> you may also want to submit this as pull request directly for the converter's code.

The only issue is that if someone wishes to somehow incorporate the Momentum optimizer this would break for them. I am not entirely aware of the potential problems with that and how exactly to go about proofing against that yet. But I will consider this and try it out. Thanks for the suggestion!
