### ISSUE TITLE
finetuning flowers colab

### ISSUE THREAD

**Issue by jmarrietar** [google-research/simclr#94]
Hi!, Thanks for the Jupyter Notebook examples. I have a question regarding `finetuning.ipynb`. The model used in the Jupyter Notebook was first `pre-trained` with ImageNet rigth?. And in the Jupyter Notebook, only the part of the fine tunning is shown. 

If i wanted to apply this method to a completely new dataset I would need to first use `--train_mode=pretrain` with my data and then `--mode=train_then_eval` . Is this correct?.

Thank you very much.

**Comment by chentingpc** [comment]
For the first question: Yes the pretraining part was done on ImageNet and is not in notebook.

For the second question, yes that'd be one use case (you could use any datasets existed in tfds or you need to replace the data input pipeline for your dataset).
