### ISSUE TITLE
Demo for detection on COCO or VOC

### ISSUE THREAD

**Issue by momo1986** [google-research/simclr#98]
Hello，
Thanks for sharing.
I want to know whether there exists the demo to integrate simclr with STA detection model like SSD/Yolov3 on COCO or VOC.

If not, is there some tips to integrate the modules?

Thanks & Regards!
Momo

**Comment by chentingpc** [comment]
Unfortunately there's no demo for detection here. You're welcomed to add one if you'd like! Will close it for now, but feel free to post back if you created something ('ll consider link your repo).
