### ISSUE TITLE
Feed Data into Pretrained Model

### ISSUE THREAD

**Issue by alirezadizaji** [google-research/simclr#99]
Hi,
I've pretrained SIMCLRv2 with my custom dataset, then I loaded graph and weights via code below:

`saver = tf.train.import_meta_graph("{}/eval_ckpt/model.ckpt-117188.meta".format(FLAGS.model_dir))
      saver.restore(sess, "{}/eval_ckpt/model.ckpt-117188".format(FLAGS.model_dir))`

now I want to feed new data into model just for watching projection_head output  with `sess.run`, which gets two arguments:
1. output which is "head_contrastive/nl_2/batch_normalization/gamma/Momentum:0", the name of last projection_head tensor
2. placeholder
 but there is no placeholder in graph, I tried to get the first conv2d layer via its name("base_model/conv2d/kernel:0") and stick the placeholder behind it but I could not.
thanks in advance

**Comment by chentingpc** [comment]
Do you have a hub module saved? I think that'd be much easier to work with, see this example: https://github.com/google-research/simclr/blob/master/colabs/load_and_inference.ipynb

**Comment by alirezadizaji** [comment]
> Do you have a hub module saved? I think that'd be much easier to work with, see this example: https://github.com/google-research/simclr/blob/master/colabs/load_and_inference.ipynb

Unfortunately no, But with estimator.predict the problem was resolved.
thanks.
